### ISSUE TITLE
Cannot start Mattermoster

### ISSUE THREAD

**Issue by marijn-mijnhost** [swordf1zh/mattermoster#1]
I've installed Mattermoster as in the documentation, but cannot start it.
```
ubuntu@server-3:/opt/mattermoster-base$ node index.js

/opt/mattermoster-base/node_modules/mattermoster/app.js:35
class Mattermoster {
^^^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/opt/mattermoster-base/index.js:1:89)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
```

```
ubuntu@server-3:/opt/mattermoster-base$ node -v
v4.2.6
```

**Comment by marijn-mijnhost** [comment]
Found it. Version of node was outdated. Updated to v10.5.0 and now it's working!
